export const ItemTypes = {
  PIECE: "piece",
  BLACKKING: "blackKing",
  BLACKQUEEN: "blackQueen",
  BLACKKNIGHTONE: "blackKnightOne",
  BLACKKNIGHTTWO: "blackKnightTwo",
  BLACKROOKONE: "blackRookOne",
  BLACKROOKTWO: "blackRookTwo",
  BLACKBISHOPONE: "blackBishopOne",
  BLACKBISHOPTWO: "blackBishopTwo",
  BLACKPAWNONE: "blackPawnOne",
  BLACKPAWNTWO: "blackPawnTwo",
  BLACKPAWNTHREE: "blackPawnThree",
  BLACKPAWNFOUR: "blackPawnFour",
  BLACKPAWNFIVE: "blackPawnFive",
  BLACKPAWNSIX: "blackPawnSix",
  BLACKPAWNSEVEN: "blackPawnSeven",
  BLACKPAWNEIGHT: "blackPawnEight",

  WHITEKING: "whiteKing",
  WHITEQUEEN: "whiteQueen",
  WHITEKNIGHTONE: "whiteKnightOne",
  WHITEKNIGHTTWO: "whiteKnightTwo",
  WHITEROOKONE: "whiteRookOne",
  WHITEROOKTWO: "whiteRookTwo",
  WHITEBISHOPONE: "whiteBishopOne",
  WHITEBISHOPTWO: "whiteBishopTwo",
  WHITEPAWNONE: "whitePawnOne",
  WHITEPAWNTWO: "whitePawnTwo",
  WHITEPAWNTHREE: "whitePawnThree",
  WHITEPAWNFOUR: "whitePawnFour",
  WHITEPAWNFIVE: "whitePawnFive",
  WHITEPAWNSIX: "whitePawnSix",
  WHITEPAWNSEVEN: "whitePawnSeven",
  WHITEPAWNEIGHT: "whitePawnEight",
};
